name: api_ekko

dependencies:

  logger: ^0.9.2
  args: ^1.6.0

  get_server: ^0.6.3
  # get_server:
  #   path: "C:/Projetos/Personal/get_server"
  # get_server:
  #   git:
  #     url: https://github.com/Katekko/get_server.git
  #     ref: master

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^3.4.1